Update : adding PodManager + HTTP Server
saisona/go-feather-slack-app pull request #5
Opened 2020-12-09 20:03 UTC by saisona

- Adding GetPods
 - Adding GetPod
 - Adding CreateJob
 - Adding CreateJobSpecWithConfigMap
 - Adding CreateJobSpecWithEnvs
 - Adding Go module

2020-12-10 21:57 UTC, cesumilo requested changes
LGTM with refactoring 👍

2020-12-10 21:57 UTC, cesumilo commented on src/go-feather-slack-app/manager/main.go
> +	fmt.Printf("Job %s has been created successfuly", job.GetName())
Instead of using `fmt` you can use `log` which suites better to server usage.

2020-12-10 21:57 UTC, cesumilo commented on src/go-feather-slack-app/manager/main.go
> +	}
```suggestion
        var config *rest.Config
        var err error
 
	if inCluster {
		config, err = rest.InClusterConfig()
		if err != nil {
			panic(err.Error())
		}
	} else {
		config, err = clientcmd.BuildConfigFromFlags("", os.Getenv("KUBECONFIG"))
		if err != nil {
			fmt.Println("ERR ", err.Error())
			panic(err.Error())
		}
	}
	
	clientSet, err := kubernetes.NewForConfig(config)
        if err != nil {
		panic(err.Error())
	}
	return &PodManager{client: clientSet}
```

2020-12-10 21:57 UTC, cesumilo commented on src/go-feather-slack-app/server/main.go
> +	http.HandleFunc("/healthz", healthz)
I don't know the difference between http and mux. Maybe worth it to take a look at [https://github.com/gorilla/mux](https://github.com/gorilla/mux)

2020-12-16 13:57 UTC, saisona commented on src/go-feather-slack-app/server/main.go
> +	http.HandleFunc("/healthz", healthz)
I'll look upon that thx for the info

2020-12-16 13:57 UTC, saisona commented on src/go-feather-slack-app/manager/main.go
> +	fmt.Printf("Job %s has been created successfuly", job.GetName())
Thanks for the info

2020-12-16 19:02 UTC, cesumilo approved these changes
LGTM

2020-12-23 11:42 UTC, cesumilo approved these changes
LGTM

2021-01-03 21:11 UTC, merged